### ISSUE TITLE
Адмінка. При внесенні правок в подію автоматично встановлюється дата останнього редагування. 

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#1]
Кроки відтворення. 
1) Створити нову подію з датою 27.12.2022 
2) Зберегти її
3) Внести будь-які правки у текст, назву, або змінити фото (припустімо, що правки вносяться 25.12.2022)
4) Зберегти зміни

Очікуваний результат:
Внесені зміни коректно відображаються. Дата події залишається 27.12.2022

Фактичний результат:
Дата події змінюється на дату внесення правок. Тобто 25.12.2022. Кожного разу, як адмін буде заходити у меню редагування події (кнопка "Детальнее"), інтерактивний календар буде автоматично встановлюватися на актуальну дату.

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check
