### ISSUE TITLE
Баг зі скролом

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#10]
Я відловив баг зі скролом про який ти писав коли тестував поле пошуку в Галереї, але відтворити його не зміг. Тож поки що хз в чому там проблема. 
У мене скрол взагалі зник. Можливо то якийсь баг браузера, але раніше я такого за ним не спостерігав (Comodo Dragon  108.0.5359.95 (64-розрядна версія))

**Comment by ilsrbn** [comment]
На это влияет высота viewport-а (видимой области).

![image](https://user-images.githubusercontent.com/71154152/209432650-a74bad8b-51d0-4884-86d7-6488d77aa708.png)

**Comment by ilsrbn** [comment]
@HeavenlyOne  Please check

**Comment by HeavenlyOne** [comment]
@ilsrbn за тонкощі версти і viewport-и я не шарю, тому адекватно перевірити не в змозі.
