### ISSUE TITLE
Адмінка. Одрук в меню редагування події. "Опубликоно"

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#2]
![Одрук-Опубликовано](https://user-images.githubusercontent.com/106679395/209407533-4228d07e-3bce-4f60-8931-b5734186b4b6.png)

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check

**Comment by HeavenlyOne** [comment]
@ilsrbn Одрук все ще присутній при створенні нової події (у ти що вже були створені, його виправлено)

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check
