### ISSUE TITLE
Адмінка. Видалення фото згортає вікно зі світлинами

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#3]
Кроки відтворення:
1) Створити нову подію (або скористуватися тією, що вже існує)
2) Додати кілька фото
3) Розгорнути меню з фотографіями 
4) Нажати на кнопку "Удалить" під будь-якою з фотографій
5) Підтвердити видалення

Очікуваний результат:
Фото видалено. Меню зі світлинами залишається розгорнутим

Фактичний результат:
Фото видалено. Меню зі світлинами автоматично згортається. 
Тобто для видалення кількох фото доведеться для кожного окремого фото повторювати процедуру. 
![Видалення_фото_1](https://user-images.githubusercontent.com/106679395/209408118-871c3a3e-9721-4be5-b78a-5bd24f2d1db9.png)
![Видалення_фото_2](https://user-images.githubusercontent.com/106679395/209408120-77e01644-a4e5-4ca9-a0ae-3f7f8ad48508.png)
![Видалення_фото_3](https://user-images.githubusercontent.com/106679395/209408121-79cf2f0c-90f9-4515-99c2-4abbd6468ae1.png)

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check
