### ISSUE TITLE
Адмінка. Засмічення стрічки подій пустими макетами

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#5]
Кроки відтворення:
1) Створити подію без назви, тексту, або фото
2) Натиснути на поле "Сохранить"
3) Закрити вікно створення події
4) Перезавантажити сторінку "Собітия"
5) Клікнути по кнопці "Детальнее" під новою подією

Очікуваний результат: 
Збереження події без назви, тексту чи фото не можливе. Подію не буде створено. 

Фактичний результат:
Хоча вікно створення нової події не закривається при натисканні поля "Сохранить" (тобто ми не бачимо візуального підтвердження того, що подію було створено), з кожним натисканням утворюється сміттєва сторінка нової події. Вони не відображаються в Галереї сайту. Не відображаються вони і після закриття панелі створення події. Проте, якщо перезавантажити сторінку "Собітия", то ми побачимо стільки нових "подій", скільки разів клікнули по поля "Сохранить". При спробу відкрити одну з таких подій у адмінці вийде помилка 404. Таким чином у меню будуть створюватися пусті макети, які треба видаляти вручну. 

NB: Було б непогано додати поп-ап вікна, які б інформували користувача, що він робить не так і які б блокували поле збереження події   
![Пусті макети подій](https://user-images.githubusercontent.com/106679395/209410272-7ffc99ff-4990-4da1-b282-18e99ca01782.png)
![Збереження новини без фото_4](https://user-images.githubusercontent.com/106679395/209410359-0e675bec-b3e1-4aa2-98c8-b695082b7395.png)

**Comment by ilsrbn** [comment]
@HeavenlyOne please check

**Comment by HeavenlyOne** [comment]
@ilsrbn Основну проблему усунено. Але події можна публікувати без фото, якщо у створеній події при редактурі видалити всі фото, то вона буде відображатися без них і система ок із цим. Може воно і непогано (події без фото взагалі) з точки зору зручності та простору для маневру адмінів, проте у Галереї воно виглядає не дуже сексуально.

**Comment by ilsrbn** [comment]
@HeavenlyOne Сделал добавление фоток опциональными + подправил отображение таких постов на клиенте

**Comment by HeavenlyOne** [comment]
@ilsrbn Nice! Мені подобається.
