### ISSUE TITLE
Адмінка. Однакова назва подій призводить до "поглинання" молодшої старшою. 

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#6]
Ррррр...писав-писав...дописав. Не встиг клацнути сабміт. Вимкнули світло. Версію 2.0 буду писати крізь гнів та відразу, тому, якщо щось буде не зрозуміло, - пиши.

Кроки відтворення:
1) Створити нову подію з назвою "Подія один" (далі Подія 1.1) з фото та текстом
2) Створити іншу подію з назвою "Подія один" (далі "Подія 1.2) зі своїми унікальними фото та текстом
3) Відкрити Подія 1.2 та внести правки
4) Відкрити Подію 1.1 та перевірити наявність внесених правок
5) Відкрити Подію 1.2 у Галереї сайту

Очікуваний результат:
Обидві події мають свої унікальні ID та ендпоінти та не впливають одна на іншу.

Фактичний результат:
Події коректно відображаються лише у вікнах анонсу у Галереї та меню "Собитія" адмінки". Якщо відкрити в адмінці Подію 1.2, то ми побачимо зміст Події 1.1, внесені та збережені тут зміни відобразяться також у змісті Події 1.1. Зміни, внесені у Події 1.1 будуть відображені у змісті Події 1.2. Якщо відкрити Подію 1.2 у Галереї сайту, то ми побачимо зміст Події 1.1.

NB: Якщо оригінальну назву події згодом змінити на вже існуючу, тієї події, що була створена раніше, то це не призведе до лінкування. Але! Якщо змінити оригінальну назву події, а потім створити нову подію з назвою, що була змінена, то система злінкує нову подію з тією, де назву було змінено.
NB2: Якщо видалити Подію 1.1, то первинний зміст Події 1.2 повернеться/відновиться. 

Відео:
https://drive.google.com/file/d/1XR81NHUKjaebEnt21ocFZDf2vUWIETkt/view?usp=sharing

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check
