### ISSUE TITLE
Сайт. Кнопки Телеграма, Інсти та контакти розробників

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#7]
Кнопки Телеграма, Інсти та посилання на контакти розробників відкривають ці сторінки у тому ж вікні, а мали би у новому.

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check

**Comment by HeavenlyOne** [comment]
@ilsrbn Телеграм та інста все ще відкриваються у тому же вікні. З соціалками розробників все ок.

**Comment by ilsrbn** [comment]
@HeavenlyOne Done
