### ISSUE TITLE
Usability issues  

### ISSUE THREAD

**Issue by HeavenlyOne** [ilsrbn/podpolye_dashboard#8]
1) В Галереї впорядковує події не за датою події (вказаною при створенні або редагуванні), а за хронологією первинного створення події в адмінці 
![Перенос дати у Галереї на компі](https://user-images.githubusercontent.com/106679395/209414937-bd89fa81-1a83-4129-a6ad-0859a02732d3.png)
2) При створенні нової події вікно створення можна закрити випадково клікнувши/тапнувши поза межамі вікна, втративши усю зроблену роботу. Було б непогано унеможливити це і додати до вікна створення кнопку або хрестик для закриття вікна без збереження результатів. 
3) У випадку, якщо при створенні події була додана лише одна фотографія, то дублює її при висвітленні новини в Галереї. Виглядає не дуже акуратно. 
4) Не працює пошук за датою (ігнорує цифри).
5) Відсутня кнопка "Вийти" з акаунта адмінки
6) Естетичне: на компі дата події в її анонсі в Галереї переноситься з однієї строки на іншу. В ідеалі, якби дата завжди була окремою строкою. 
![Перенос дати у Галереї на компі](https://user-images.githubusercontent.com/106679395/209414861-73322f7e-e4c3-4ad5-bc56-af4c453033b5.png)
7) При наведенні курсора на фото у вікні «Події» індикатор курсора не змінюється, натякаючи на те, що її можна розгорнути на весь екран.

**Comment by ilsrbn** [comment]
@HeavenlyOne Please check (exluding 4)

**Comment by HeavenlyOne** [comment]
1-3, 5-7 - checked
